version: "3.9"

services:

  database:
    build: ./database
    container_name: greenpath_db
    environment:
      POSTGRES_USER: vinny
      POSTGRES_PASSWORD: vinny!
      POSTGRES_DB: green_path
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: greenpath_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/green_path
      SPRING_DATASOURCE_USERNAME: vinny
      SPRING_DATASOURCE_PASSWORD: vinny!
      SPRING_DATASOURCE_NAME: clientes_greenpath
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: greenpath_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:

networks:
    default:
      driver: bridge
